env: standard
runtime: nodejs10
service: default
instance_class: F2

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js|xml|png|txt|otf|css))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|xml|png|txt|otf|css)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301

default_expiration: "5m"
